### ISSUE TITLE
Joint first author/equal contrib

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-poa-xml-generation#129]
This is from the .py details:

self.contrib = SubElement(self.contrib_group, "contrib")

```
        self.contrib.set("contrib-type", contributor.contrib_type)
        if contributor.corresp == True:
            self.contrib.set("corresp", "yes")
        if contributor.equal_contrib == True:
            self.contrib.set("equal_contrib", "yes")
        if contributor.auth_id:
            self.contrib.set("id", "author-" + str(contributor.auth_id))
```

Is this factored into the PoA workflow? 
We need to review the EJP SQL output and the xml to make sure we know what the procedure is and how it is taken

**Comment by gnott** [comment]
Hi @Melissa37 - could you please comment on whether as an enhancement you'd like to specify author equal_contrib values. I don't think we have the data in the CSV data, but maybe you are able to get it?
