### ISSUE TITLE
XML generation failed in production

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-poa-xml-generation#133]
document: 3686_1_supp_mat_highwire_zip_53483_n4w55s.zip
doi: 10.7554/eLife.02482

Failed in production workflows.

The file processed correctly on dev environment, and on live environment after restarting workers. It also processed on the live environment after commenting out (for debugging purposes) the exception around xml generation.

``xml_generation.py`` function ``instantiate_article`` the ``try:`` on L34 somehow raises an exception.

In the XML log:

```
2014-05-01 12:00:10,112 INFO in instantiate_article for 2482
2014-05-01 12:00:10,112 INFO in instantiate_article for 2482
2014-05-01 12:00:10,112 INFO in instantiate_article for 2482
2014-05-01 12:00:10,128 ERROR could not create article class
2014-05-01 12:00:10,128 ERROR could not create article class
2014-05-01 12:00:10,128 ERROR could not create article class
```

If this happens again, suggestion is add more logging and exception handling to the ``instantiate_article`` to better understand which particular part fails between L34 and L41.

**Comment by gnott** [comment]
Because POA articles are packaged only once a day, the temporary fix for to restart the processes has been changed to once a day instead of once per hour. Time chosen is 23:27 UTC each day. 

The bug of caching old CSV data probably still remains, but it should still be working with a daily restart.

**Comment by Melissa37** [comment]
Hey Graham, can we close this or do we need to add to a JIRA issue?

**Comment by gnott** [comment]
It's here http://jira.elifesciences.org:8080/browse/ELPP-792

I deployed the potential fix May 12th and so far so good.
