### ISSUE TITLE
Inclusion of full middle name in xml

### ISSUE THREAD

**Issue by lfb00** [elifesciences/elife-poa-xml-generation#156]
At the moment only the initial of the middle name is included in the xml, even when a full middle name is entered. It would be good to have this included as there have been a few authors who go by their middle name.

**Comment by Melissa37** [comment]
Hi there

06262 was PoA'd yesterday and the author's middle name has been truncated to an initial only. We've checked the CSV output from EJP and it is listed in full in the middle name section of the CSV output: ejp_query_tool_query_id_177_POA_Author_2015_05_13_eLife

James is not here today, but Sam and I have dug about and found this.

Can you identify where the error occurred? Looks like it's in the eLife Bot process.

Cheers
M

**Comment by gnott** [comment]
In review of the code, it is not truncating any middle name values when generating PoA XML. 

In the case of article 06262, the source data from the CSV files has the middle name and surname together as a single value in the surname field. The middle name field is blank.
