### ISSUE TITLE
Travis-ci

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-poa-xml-generation#197]
Automate travis-ci for testing.

* Inject basic ``settings.py`` or rename ``example-settings.py`` as it before script
* Bonus points: install PDF decapitator v2 dependencies and write a test for decapitator

**Comment by Melissa37** [comment]
Hey Graham, another for JIRA transfer?

Cheers
M

**Comment by gnott** [comment]
In JIRA, http://jira.elifesciences.org:8080/browse/ELPP-927
