### ISSUE TITLE
Upgrade to  JATS 1.1d3

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-poa-xml-generation#208]
We're upgrading the VoR content to  JATS 1.12d, so assume we should do the same for PoA at some point?

M

**Comment by gnott** [comment]
I am looking for changes between the version we use now and the new proposed version.

Do you mean JATS 1.1d1  to JATS 1.1d2?

**Comment by gnott** [comment]
http://jats.nlm.nih.gov/publishing/tag-library/1.1d2/chapter/version-1.1d2-chg.html  Looks like only ``<ruby>`` and ``<rb>`` tags are incompatible changes between the two versions, so switching should be easy.

**Comment by gnott** [comment]
This will now be to version JATS 1.1d3.  http://jats.nlm.nih.gov/publishing/tag-library/1.1d3/chapter/version-1.1d3-chg.html  has no additional backward compatibility issues.
