### ISSUE TITLE
Get tests of JATS XML generation to build on Alfred

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-poa-xml-generation#296]

**Comment by gnott** [comment]
Final one for Alfred to build please @giorgiosironi  https://github.com/elifesciences/jats-generator

**Comment by gnott** [comment]
Jenkins file is in https://github.com/elifesciences/jats-generator/blob/develop/Jenkinsfile. Should this be listed as a "library-jats-generator" in the pipelines @giorgiosironi? I just wanted to check before I close the issue.

**Comment by giorgiosironi** [comment]
Yes, the mainline build from `develop` is in https://alfred.elifesciences.org/job/libraries/
I am putting new builds into a subfolder due to their high number.

**Comment by gnott** [comment]
Mystery solved! Thanks @giorgiosironi
