### ISSUE TITLE
Names for data supplements files when packaging PoA zip file

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-poa-xml-generation#312]
In the refactored code in the new package-poa project at https://github.com/elifesciences/package-poa, the file names for data supplement files as well as the zip file name (and PDF file name) themselves are configurable using a file name pattern. eLife can use the elife naming pattern, and potentially the file names can be changed for other users.

A question for you please @Melissa37: below is an example of the digital supplement file names of the files found inside the ``"ds.zip"`` file. There is no change so far - it has been like this for years - although I wanted to check and see if you would like to name the files differently

```
elife_poa_e12717_Figure_1_figure_supplement_1.pdf
elife_poa_e12717_Figure_2_figure_supplement_1.pdf
elife_poa_e12717_Figure_2_figure_supplement_2.pdf
elife_poa_e12717_Figure_3_figure_supplement_1.pdf
elife_poa_e12717_Figure_3_figure_supplement_2.pdf
elife_poa_e12717_Figure_3_figure_supplement_3.pdf
elife_poa_e12717_Figure_4_figure_supplement_1.pdf
elife_poa_e12717_Figure_4_figure_supplement_2.pdf
elife_poa_e12717_Figure_6_figure_supplement_1.pdf
elife_poa_e12717_Figure_6_figure_supplement_2.pdf
elife_poa_e12717_Figure_7_figure_supplement_1.pdf
elife_poa_e12717_Figure_8_figure_supplement_1.pdf
elife_poa_e12717_Supplementary_File_1.xls
elife_poa_e12717_Supplementary_File_2.xlsx
elife_poa_e12717_Supplementary_File_3.xls
elife_poa_e12717_Video_1.mov
elife_poa_e12717_Video_10.mov
elife_poa_e12717_Video_11.mov
elife_poa_e12717_Video_12.mov
elife_poa_e12717_Video_2.mov
elife_poa_e12717_Video_3.mov
elife_poa_e12717_Video_4.mov
elife_poa_e12717_Video_5.mov
elife_poa_e12717_Video_6.mov
elife_poa_e12717_Video_7.mov
elife_poa_e12717_Video_8.mov
elife_poa_e12717_Video_9.mov
```

The process is basically it reads in the EJP ``manifest.xml`` file, gets the title of each file and uses a formatted title, and ``elife_poa_e12717`` is added to the start of the name.

I was wondering if you care for changing this at all at this stage.

One idea I was thinking is to make it aware of an article version, if supplied to it when it repackages, so the internal files could have names that include the version number, and use hypens instead of underscores, etc.

**Comment by Melissa37** [comment]
Hi Graham

I am happy with this, and I am not sure it's worth versioning the files for PoA.

@JGilbert-eLife do you have any opinion on this?

We've never had any complaints so I am inclined to spend our effort elsewhere.

M
