### ISSUE TITLE
Implement an exception handling strategy

### ISSUE THREAD

**Issue by davidcmoulton** [elifesciences/elife-poa-xml-generation#94]
Make it easier for users to recover from runtime errors by implementing an exception handling strategy to provide meaningful error messages when things go wrong.

This is likely to save time and frustration down the line, and also to make future enhancement quicker and easier.

**Comment by Melissa37** [comment]
Hey Graham, another for JIRA transfer?

Cheers
M

**Comment by gnott** [comment]
Added http://jira.elifesciences.org:8080/browse/ELPP-928
